login: &login
  adapter: mysql2
  host: localhost
  username: root
  password:

development: &development
  database: laya
  <<: *login

test: &test
  database: laya_test
  <<: *login

production: &development
  database: laya
  <<: *login